apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: morriski/gomessage-operator
    context: .
    docker:
      dockerfile: ./operator/Dockerfile
  - image: morriski/gomessage-conference
    context: .
    docker:
      dockerfile: ./conference/Dockerfile

deploy:
  helm:
    releases:
      - name: gomessage  
        chartPath: k8s/
        valuesFiles: 
          - k8s/values.yaml
        values:
          operator_image: morriski/gomessage-operator
          conference_image: morriski/gomessage-conference