apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Chart.Name }}
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: connport
              containerPort: 8001
              protocol: TCP
          env:
            - name: KUBECONFIG
              value: "IN_CLUSTER"
            - name: NAMESPACE
              value: "{{ .Release.Namespace }}"
