apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
rules:
- apiGroups: [""]
  resources: [ "services", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Chart.Name }}
  apiGroup: ""