apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}
  labels:
    app: gomessage-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
